### ISSUE TITLE
Data Structures 

### ISSUE THREAD

**Issue by Amisha-here** [Amisha-here/Data-Structures#1]
Some basic Algorithms of graph data structure written in C/C++
Keep on adding the algorithms for different data structures.

**Comment by pradumio** [comment]
@Amisha-here I can add search and sort algorithm cpp codes. Can you assign me?

**Comment by jakansha2001** [comment]
I can add implementation of stack in both array and linked list. Can i work on this issue?

**Comment by dj107** [comment]
Can i add the readme file which is missing?

**Comment by Amisha-here** [comment]
> @Amisha-here I can add search and sort algorithm cpp codes. Can you assign me?

yes sure

**Comment by Amisha-here** [comment]
> Can i add the readme file which is missing?

go ahead sure

**Comment by Amisha-here** [comment]
> I can add implementation of stack in both array and linked list. Can i work on this issue?

yes you can

**Comment by jakansha2001** [comment]
@Amisha-here please assign me this issue

**Comment by rudrakshi99** [comment]
@Amisha-here I want to add backtracking algorithms. Can you assign me?

**Comment by unnatijain99** [comment]
@Amisha-here can I add heap sort time algorithm and it's time complexity?

**Comment by Amisha-here** [comment]
> @Amisha-here can I add heap sort time algorithm and it's time complexity?

yeah sure

**Comment by tarunjain1st** [comment]
do we need to get assigned or simply we can add the file and make the pull requests

**Comment by tarunjain1st** [comment]
@Amisha-here can i add Johnson’s algorithm

**Comment by SMITVASOYA** [comment]
hello, if I add the Dijkstra algorithm using CPP can you accept it?

**Comment by padmaja-22** [comment]
I can add algorithms of trees , graphs and recursive algorithms. Can u assign me this?

**Comment by Mohit123singh** [comment]
I can add all Sorting Algorithms and some questions related to algorithms..Can u Please assign this work to me.?

**Comment by ANKITAKHAN** [comment]
hey @Amisha-here , can I add searching and sorting algorithms to this?

**Comment by deekshadaga** [comment]
can i add merge sort ?

**Comment by deekshadaga** [comment]
can i add kadane's algo / Quick sort / N-Queen problem or something ??

**Comment by urjitasharma11** [comment]
Hey, can I add some problems related to dynamic programming?

**Comment by Renu-code** [comment]
i can add merge sort/quick sort ..can i work on this issue?

**Comment by ANUJAGRAWAL2000** [comment]
> Some basic Algorithms of graph data structure written in C/C++
> Keep on adding the algorithms for different data structures.

Can I add Binary Tree related Solutions like(i)Finding Largest BST in BT (ii)All Nodes At Kth Distance etc?

**Comment by rudrakshi99** [comment]
Hey @Amisha-here , will you please add hacktoberfest  label in your repo according to the latest updates. Please check them [here](https://hacktoberfest.digitalocean.com/hacktoberfest-update).

**Comment by ANUJAGRAWAL2000** [comment]
Hii @Amisha-here please add hacktoberfest Label in Your REPO..
Thanks in Advance

**Comment by deekshadaga** [comment]
Hey! @Amisha-here please add hactorberfest topic to your repository and please merge my pull request , Thanks in advance !

**Comment by jakansha2001** [comment]
Can you also label this pull request as "hacktoberfest-accepted"?

**Comment by ManasUniyal** [comment]
Hey @Amisha-here I want to add the implementation of minimum spanning tree using Prim's algorithm.
Can you please assign me to this task?

**Comment by Dopiumistfg** [comment]
Can I add a basic 2d sorter
